### ISSUE TITLE
"cannot have source text after column" should be a warning, not an error

### ISSUE THREAD

**Issue by GitMensch** [eclipse/che-che4z-lsp-for-cobol#1042]
Because compilation just ignores it, doesn't it?

**Comment by temanbrcom** [comment]
Hi @GitMensch,

Sorry, but I am a little confused. Do you mean the text after column 80 or the check that statements should start in areas A/B?

Kind regards,
Andrei Temnikov

**Comment by GitMensch** [comment]
The title was confusing in any case. There is a check for text after column 80 (which I suggested to make adjustable in #1038, at least internally), and as the text found there is to be ignored by COBOL compilers it should be a warning, not an error.

**Comment by temanbrcom** [comment]
It seems that the IBM COBOL parser throws a compilation error in this case. Also, Zowe may show some strange behavior in this case - crate a sequential dataset member instead of LRECL 80, trim the chars after column 80, or even refuse to upload the file. So we decided to leave it with "Error" severity to prevent unexpected behavior.

Kind regards,
Andrei Temnikov
