### ISSUE TITLE
Support glob patterns in copybook directories

### ISSUE THREAD

**Issue by VitGottwald** [eclipse/che-che4z-lsp-for-cobol#1533]
I would like to be able to specify patterns for copybook folders like

```json
	"cobol-lsp.cpy-manager.paths-local": [
		"copy/*"
```

The use case assumes that there are unique file names in the `copy/*` folders. In case two files with the same name `X` exist in `copy/A/X` and in `copy/B/X` it is undefined which one will be used.

**Comment by ishche** [comment]
It should be an error.

**Comment by ishche** [comment]
Also, what do you think about this style? 
copy/* - all copy books in the folder
copy/** - all copybooks in folder and subfolders
**/copy/* - all 'copy' folders in the workspace can contain copybooks

**Comment by slavek-kucera** [comment]
in hlasm extension, we support `*`, `**` and `?` (arbitrary character, arbitrary character including directory separators, single character).

Note for the implementer: consider "user errors" like specifying "/" or "C:\", or cycles on the filesystem due to symlinks...

**Comment by RedGoldPhoenix** [comment]
Hello 
That's an interesting topic because I use this plugin :).
It is possible to give the possibility to the plugin to manage 2 branches in parallel
I explain my issue.
I created on the same repo 2 branches, my cobol are on a branch and my copybook on an other branch  
Today when I'm on a Cobol, I can't have access to the copybooks to read them.
Do you believe you can add this feature ?
Best Regards.

**Comment by slavek-kucera** [comment]
Hello @RedGoldPhoenix,
I don't think this feature was meant to interact with git in any way. However, using `git worktree` would give you the ability to have multiple branches checked out at the same time in various directories.

**Comment by RedGoldPhoenix** [comment]
> Hello @RedGoldPhoenix, I don't think this feature was meant to interact with git in any way. However, using `git worktree` would give you the ability to have multiple branches checked out at the same time in various directories.

If technically is is possible that could be great to include it in the plugin.
After I have an other challenge.
If I have 4 branches for 2 releases on the same repo how I can parameter the tool to be sure I can connect my RELASE1/subsystem/Cob with my RELASE1/subsystem/Copy and RELASE2/subsystem/Cob with my RELASE2/subsystem/Copy because I don't want that the RELASE1/subsystem/Cob read the RELASE2/subsystem/Copy as versions could be have different.

I know that is more complex ..
Best regards

**Comment by ishche** [comment]
https://github.com/eclipse/che-che4z-lsp-for-cobol/issues/698

**Comment by azarrafa** [comment]
hello,

This feature is implemented yet or not in the version 1.1.0 ?

Regards,

**Comment by zimlu02** [comment]
Hi @azarrafa ,
no, it has not been released yet.
It should be part of the upcoming release though.

**Comment by azarrafa** [comment]
Hello,
Any updates on this new feature.
Thanks

**Comment by zimlu02** [comment]
Hello @azarrafa,
thanks for checking on this.
This feature has been released with the latest [v1.1.1 version](https://github.com/eclipse/che-che4z-lsp-for-cobol/releases/tag/1.1.1).
I am closing this ticket, however, feel free to reopen or just share your comments.
Thank you.

**Comment by azarrafa** [comment]
Thanks @zimlu02 and great job btw.
