### ISSUE TITLE
Continuation line cause a semantic error

### ISSUE THREAD

**Issue by grianbrcom** [eclipse/che-che4z-lsp-for-cobol#414]
## Description ##

The continuation line cause a semantic error.

## Steps to reproduce ##

1. Open VSCode or Theia with an installed extension
1. Create a .cbl file that will contain the following piece of code:
```
       Identification Division.
       Program-id. HELLO-WORLD.
       Data Division.
       Working-Storage Section.
           01 User-Num1 PIC 9(9).
       Procedure Division.
        100-Print-User.
           Move 123456789 
      -       To User-Num1.
       End program HELLO-WORLD
```
1. You will see an error on the line `Move 123456789`

## Expected behavior ##

No semantic error

## Screenshots ##

![image](https://user-images.githubusercontent.com/60617592/86383624-7acf3800-bc8e-11ea-890c-ec9d07db3a90.png)

## Environment ##
 
OS: Linux
IDE: VS Code

**Comment by zacanbrcom** [comment]
The issue is invalid since the snippet produced by the user contains both errors by definition:
- a semantic error (blue underline) since the COBOL compiler will merge ```10``` + ```TO``` in one token without spaces so that ```MOVE``` statement will now contains a variable called ```10TO``` that is not defined in WS section or in any copybook
- a syntax error (red underline) since the ```TO``` keyword is now part of the variable name and there is a missed ```TO``` token when the extension parse that instruction.
As reference the following example shows valid example of continuation lines, applied to numeric literals:

```
                                                       MOVE 999999999909
      -        1234 TO WS-CUST-NUM-4.
           DISPLAY WS-CUST-NUM-4.
```
```
           MOVE 1234
      -            5678 TO WS-CUST-NUM-5.
           DISPLAY WS-CUST-NUM-5.
```

**Comment by temanbrcom** [comment]
It misplaces the variable usage after the string literal ending on the continuation line. For example,
```
1       MOVE 'start
2       ' finish' to VARNAME.
```
will not show the VARNAME on line 2 as expected but on line 1.

**Comment by temanbrcom** [comment]
The reason is the same as in #413
